### ISSUE TITLE
Possibility to register server commands to Better Chat on server join

### ISSUE THREAD

**Issue by GreepTheSheep** [codecat/tm-better-chat#21] opened 2021-12-20 21:20 UTC
When we join a server, Better Chat sends automatically `/chatformat json`, would be cool that the server responds with a json string containing all the server commands, and then Better Chat can handle that when we use slash on it.

**Comment by codecat** [comment] 2021-12-20 21:26
Duplicate of #7

**Closed by codecat** 2021-12-20 21:26 UTC
